CREATE TABLE IF NOT EXISTS `flt_data` (
  `id_spam` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `from_spam` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `mail_spam` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id_spam`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

INSERT INTO `flt_data` (`id_spam`, `from_spam`, `mail_spam`) VALUES
(1, 'Angel', 'bonser@gmail.com'),
(2, 'Mackenzie', 'lifestile@msn.com'),
(3, 'Mya', 'lightsoul@gmail.com'),
(4, 'Chase', 'pitfighter@hotmail.com'),
(5, 'Jackson', 'nogood87@yahoo.com'),
(6, 'Anthony', 'kidrock@msn.com'),
(7, 'Anthony', 'dirtbill@yahoo.com'),
(8, 'Sydney', 'lifestile@msn.com'),
(9, 'Layla', 'john@hotmail.com'),
(10, 'Jake', 'flyman@gmail.com'),
(11, 'crazyfrog', 'friend35@hotmail.com'),
(12, 'Angel', 'thebest@hotmail.com'),
(13, 'Sean', 'lightsoul@gmail.com'),
(14, 'Isaac', 'pitfighter@hotmail.com'),
(15, 'Aiden', 'freelife@yahoo.com'),
(16, 'Xavier', 'lifestile@msn.com'),
(17, 'Lillian', 'friend35@hotmail.com'),
(18, 'Angel', 'friend35@hotmail.com'),
(19, 'Sofia', 'fifa55@yahoo.com'),
(20, 'David', 'gobiz@gmail.com'),
(21, 'Morgan', 'deadman@gmail.com'),
(22, 'Thomas', 'heyjew@msn.com'),
(23, 'Serenity', 'freeman@hotmail.com'),
(24, 'Lucas', 'lightsoul@gmail.com'),
(25, 'coolman', 'fifa55@yahoo.com'),
(26, 'Emily', 'freelife@yahoo.com'),
(27, 'Eli', 'flyman@gmail.com'),
(28, 'heyjew', 'cooler111@yahoo.com'),
(29, 'Caroline', 'lightsoul@gmail.com'),
(30, 'Rebecca', 'greenwood@webtown.com'),
(31, 'Jack', 'heyjew@msn.com'),
(32, 'Olivia', 'lightsoul@gmail.com'),
(33, 'Cameron', 'lightsoul@gmail.com'),
(34, 'Valeria', 'getjoy@msn.com'),
(35, 'Leslie', 'incomeppc@hotmail.com'),
(36, 'Tyler', 'quaker@yahoo.com'),
(37, 'John', 'deadman@gmail.com'),
(38, 'Amelia', 'steep777@yahoo.com'),
(39, 'Michelle', 'goodboy@yahoo.com'),
(40, 'Natalie', 'eblanned@yahoo.com'),
(41, 'Ava', 'crazyfrog@hotmail.com'),
(42, 'Nathaniel', 'getjoy@msn.com');